name: workflow-1
on: workflow_dispatch
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: echo "The initialization of job#1 is started"
      - name: finishProcess
        run: echo "The job was accomplished"
